CREATE TABLE IF NOT EXISTS codes (code INT NOT NULL, drinks VARCHAR(255) NOT NULL, food VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS food (event VARCHAR(255), item VARCHAR(255), description VARCHAR(255), orders VARCHAR(255));
CREATE TABLE IF NOT EXISTS drinks (event VARCHAR(255), item VARCHAR(255), description VARCHAR(255), orders VARCHAR(255));
